# Generated by Django 5.1.4 on 2025-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_bio_user_cover_photo_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
