# Generated by Django 5.1.4 on 2025-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_post_photo_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
