# Generated by Django 5.1.4 on 2025-01-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("Public", "Público"), ("Followers", "Somente seguidores")],
                default="public",
                max_length=10,
            ),
        ),
    ]
