# Generated by Django 5.1.4 on 2025-01-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Público"), ("followers", "Somente seguidores")],
                default="public",
                max_length=10,
            ),
        ),
    ]
